# Generated by Django 5.1 on 2024-11-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_multiple',
            field=models.BooleanField(default=False),
        ),
    ]
